$(document).ready(function () {indexDict['en'] = [{ "title" : "eSignatures ", 
"url" : "esignatures.html", 
"breadcrumbs" : "Sertifi Support Site \/ eSignatures ", 
"snippet" : "Close the deal faster by going 100% digital with Sertifi eSignatures (formerly ClosingPro). The solution is fast, secure, and legal. Never wait days or weeks for signed agreements. Secure, compliant, and fully branded toward your organization, Sertifi is the perfect tool to execute agreements. Delig...", 
"body" : "Close the deal faster by going 100% digital with Sertifi eSignatures (formerly ClosingPro). The solution is fast, secure, and legal. Never wait days or weeks for signed agreements. Secure, compliant, and fully branded toward your organization, Sertifi is the perfect tool to execute agreements. Delight customers with an easy way to sign – anywhere, anytime, and from any Internet-enabled device, or capture in-person eSignatures on mobile devices or tablets. Sertifi offers flexible workflows, ways to track, manage, and report on your agreements sent for eSignatures, and use admin settings. " }, 
{ "title" : "Send A File ", 
"url" : "esignatures.html#UUID-9ae9e2b1-552f-9dfc-453e-9cfc07ad149c_UUID-a83cb710-7b7c-1bda-d39a-9adfbfc31872", 
"breadcrumbs" : "Sertifi Support Site \/ eSignatures \/ Send A File ", 
"snippet" : "If you use Sertifi eSignatures and you're a Sertifi Admin or higher, you can send files to clients for signature. A file contains reference and signature documents, participant management, and all file maintenance activities. Learn more about Roles in your Sertifi portal ....", 
"body" : "If you use Sertifi eSignatures and you're a Sertifi Admin or higher, you can send files to clients for signature. A file contains reference and signature documents, participant management, and all file maintenance activities. Learn more about Roles in your Sertifi portal . " }, 
{ "title" : "eAuthorizations ", 
"url" : "eauthorizations.html", 
"breadcrumbs" : "Sertifi Support Site \/ eAuthorizations ", 
"snippet" : "With Sertifi eAuthorizations you can rapidly and securely collect payment authorization forms electronically, while giving your customers a completely branded experience. At the time of online capture, the payment is instantly verified. Authorization forms are secure and payment data is tokenized. T...", 
"body" : "With Sertifi eAuthorizations you can rapidly and securely collect payment authorization forms electronically, while giving your customers a completely branded experience. At the time of online capture, the payment is instantly verified. Authorization forms are secure and payment data is tokenized. This ensures you collect payment authorization in a PCI-compliant way, and eliminate any physical authorization forms. Using Sertifi eAuthorizations, you send a file in the Sertifi Portal that contains the authorization form that you upload to the Document Library. Then, you can easily attach the authorization form, along with payment information, for future transactions. " }, 
{ "title" : "Get Started ", 
"url" : "get-started.html", 
"breadcrumbs" : "Sertifi Support Site \/ eAuthorizations \/ Get Started ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Roles ", 
"url" : "roles.html", 
"breadcrumbs" : "Sertifi Support Site \/ Roles ", 
"snippet" : "There are five Sertifi roles that can access the Sertifi portal, regardless of whether you use Sertifi eSignatures, ePayments, or eAuthorizations. It's important to understand these different roles, as each role can perform a selected set of functions to ensure that your clients' signing experience ...", 
"body" : "There are five Sertifi roles that can access the Sertifi portal, regardless of whether you use Sertifi eSignatures, ePayments, or eAuthorizations. It's important to understand these different roles, as each role can perform a selected set of functions to ensure that your clients' signing experience goes smoothly, and documents are maintained in a sustainable and efficient manner. If you're assigned one of the following Sertifi roles, and need more permissions, contact the Sertifi Super Admin for your portal. Only Super Admins can make changes to your permissions or assign you a new role. The following table shows the default permissions enabled for each role. Permission User Admin Auditor Power Admin Super Admin Update personal info √ √ √ √ Add\/remove contacts √ √ √ Update portal settings, email templates, and signing room experience √ Access the Document Library √ √ √ √ Search by FileID √ √ √ View admins √ √ √ View Users √ √ √ Create admins\/users √ Create security groups √ Resend activation link √ √ View their own files √ √ √ √ View other user files √ Bulk send √ √ Add markups √ √ Sign documents √ √ √ √ Send documents for signature √ √ √ Send authorizations √ √ √ Send payments √ √ √ View payment information (See Tip below) Edit sending page defaults √ √ Regardless of role level, no user can view payment information by default. All users, including Super Admins, must be added to the appropriate security group in order to view payment information. " }
]
$(document).trigger('search.ready');
});